align_assignment = true
align_conditional = true
align_matrix = false
align_pair_arrow = true
align_struct_field = true
always_for_in = true
annotate_untyped_fields_with_any = false
conditional_to_if = true
format_docstrings = false
import_to_using = false
indent = 4
indent_submodule = false
join_lines_based_on_source = true
long_to_short_function_def = false
margin = 120
pipe_to_function_call = false
remove_extra_newlines = true
short_to_long_function_def = true
trailing_comma = false
whitespace_in_kwargs = true
whitespace_typedefs = false
